var beginnerInventory = require("./inventoryJSON");

var character = {
    "Name" : "",
    "Level" : 0,
    "Experience" : 0,
    "Gold" : 1000,
    "ExperienceToLevelUp" : 100,
    "TrainingPoints" : 5,
    "BaseHP" : 50,
    "MaxHP" : 50,
    "CurrentHP" : 50,
    "BaseSP" : 15,
    "MaxSP" : 15,
    "CurrentSP" : 15,
    "BaseMP" : 0,
    "MaxMP" : 0,
    "CurrentMP" : 0,
    "Strength" : 0,
    "CurrentStrength" : 0,
    "Dexterity" : 0,
    "CurrentDexterity" : 0,
    "Endurance" : 0,
    "CurrentEndurance" : 0,
    "Intelligence" : 0,
    "CurrentIntelligence" : 0,
    "Willpower" : 0,
    "CurrentWillpower" : 0,
    "Agility" : 0,
    "CurrentAgility" : 0,
    "MeleeDef" : 0,
    "CurrentMeleeDef" : 0,
    "RangedDef" : 0,
    "CurrentRangedDef" : 0,
    "SpellDef" : 0,
    "CurrentSpellDef" : 0,
    "Earth" : .95,
    "CurrentEarth" : .95,
    "Water" : .95,
    "CurrentWater" : .95,
    "Air" : .95,
    "CurrentAir" : .95,
    "Fire" : .95,
    "CurrentFire" : .95,
    "Ice" : .95,
    "CurrentIce" : .95,
    "Thunder" : .95,
    "CurrentThunder" : .95,
    "Light" : .95,
    "CurrentLight" : .95,
    "Dark" : .95,
    "CurrentDark" : .95,
    "CurrentWeaponID" : 1,
    "Inventory" : beginnerInventory()
}

module.exports = character;