var character = {
    "Name" : "",
    "Level" : 0,
    "Experience" : 0,
    "Gold" : 100,
    "ExperienceToLevelUp" : 100,
    "TrainingPoints" : 0,
    "BaseHP" : 50,
    "MaxHP" : 50,
    "CurrentHP" : 50,
    "BaseSP" : 15,
    "MaxSP" : 15,
    "CurrentSP" : 15,
    "BaseMP" : 0,
    "MaxMP" : 0,
    "CurrentMP" : 0,
    "Strength" : 0,
    "Dexterity" : 0,
    "Endurance" : 0,
    "Intelligence" : 0,
    "Willpower" : 0,
    "Agility" : 0,
    "CurrentWeaponID" : 1,
    "CurrentArmorID" : 1,
    "CurrentShieldID" : 1,
}

module.exports = character;